github_url="https://github.com/quarkusio/quarkus-quickstarts.git"
test_results="testResults"
tag_version="2.7.2.Final"
environment_variable="MODE=java"
ubuntu_packages="git wget tar"
maven_version="3.8.5"
